use std::path::PathBuf;

use log::error;
use rusty_engine::fileutils::get_home_path;

use super::dirchecks::{client_dirs_exist, server_dirs_exist};

/// Cleanup all directories and files generated by the app (this is to uninstall the game)
pub fn dir_cleanup() {
    let _home = get_home_path();
    
    if client_dirs_exist() {
        // Cleanup client directories
        if let Err(why) = std::fs::remove_dir("./client_config") {
            error!("Unable to cleanup dir 'client_config': {why:?}");
        }
    }

    if server_dirs_exist() {
        // Cleanup server directories
        if let Err(why) = std::fs::remove_dir("./server_config") {
            error!("Unable to cleanup dir 'server_config': {why:?}");
        }
    }

    let log_path = PathBuf::from("./logs");

    if log_path.exists() {
        if let Err(why) = std::fs::remove_dir(log_path) {
            error!("Unable to cleanup dir 'logs': {why:?}");
        }
    }
}
